# Generated by Django 4.1.2 on 2022-11-05 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calculatorapi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slack_username', models.CharField(max_length=120)),
                ('operation_type', models.CharField(max_length=120)),
                ('x', models.FloatField(blank=True)),
                ('y', models.FloatField(blank=True)),
                ('result', models.BigIntegerField()),
            ],
        ),
    ]
