# Generated by Django 4.1.2 on 2022-11-05 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_calculatorapi_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculatorapi',
            name='x',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calculatorapi',
            name='y',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
